Repository microsoft/vscode-java-dependency, pull requests merged in 2020-11, with the labels that each got.

#366 fix: Validate input & change pre-fill value
  src/explorerCommands/new.ts
  src/explorerCommands/rename.ts
  src/explorerCommands/utils.ts
Labels: regression

#369 chore: Enable checkstyle for Java
  .gitignore
  .travis.yml
  .vscode/settings.json
  gulpfile.js
  jdtls.ext/check_style.xml
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ExtUtils.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/JarFileContentProvider.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/org/eclipse/jdt/internal/jarpackager/JarPackageUtil.java
  jdtls.ext/pom.xml
Labels: eng

#350 Support custom task to export jar
  jdtls.ext/com.microsoft.jdtls.ext.core/plugin.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/CommandHandler.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  package-lock.json
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/exportJarFileCommand.ts
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/IStepMetadata.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
  src/exportJarSteps/ResolveMainClassExecutor.ts
  src/exportJarSteps/utility.ts
  src/extension.ts
  src/java/jdtls.ts
  src/views/nodeCache/Trie.ts
Labels: enhancement

#375 chore: Send event for 'query-expfeature'
  package-lock.json
  package.json
  src/ExperimentationService.ts
Labels: eng

#377 Prepare for 0.15.0 release
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
Labels: eng

#379 Fix: Missing class files when exporting jar
  src/exportJarSteps/GenerateJarExecutor.ts
Labels: bug

#376 fix: Cannot show the content of a referenced jar
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageParams.java
  src/views/packageRootNode.ts
Labels: bug

#381 Fix: Missing class files when exporting jar
  src/exportJarSteps/GenerateJarExecutor.ts
Labels: regression

#383 chore: Update dependencies
  .travis.yml
  package-lock.json
  package.json
  src/views/dependencyDataProvider.ts
Labels: eng

#384 Fix: Target path is wrong when exporting jar from a workspace node
  src/exportJarFileCommand.ts
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/IExportJarStepExecutor.ts
  src/exportJarSteps/IStepMetadata.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
  src/exportJarSteps/ResolveMainClassExecutor.ts
  src/exportJarSteps/utility.ts
  src/views/dependencyDataProvider.ts
Labels: regression

#388 chore: Fix error in CI test process
  .travis.yml
  extension.bundle.ts
  src/extension.ts
  test/gradle-suite/projectView.test.ts
  test/index.ts
  test/maven-suite/projectView.test.ts
  test/shared.ts
  test/simple-suite/projectView.test.ts
Labels: eng

#371 refactor: Fix unused locals/parameters and implicit returns
  src/controllers/libraryController.ts
  src/explorerCommands/delete.ts
  src/explorerCommands/new.ts
  src/explorerCommands/rename.ts
  src/explorerCommands/utility.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/ResolveMainClassExecutor.ts
  src/views/containerNode.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/documentSymbolNode.ts
  src/views/fileNode.ts
  src/views/hierarchicalPackageNode.ts
  src/views/nodeCache/Trie.ts
  src/views/packageNode.ts
  src/views/projectNode.ts
  src/views/symbolNode.ts
  test/shared.ts
  test/suite/extension.test.ts
  tsconfig.json
Labels: eng

#391 feat: Update project from project node in explorer
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/views/dependencyDataProvider.ts
Labels: enhancement

#394 fix: Cannot show Chinese project name
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
Labels: bug

#395 refactor: Change 'Reveal in Java Projects' to 'Reveal in Java Projets Explorer'
  package.nls.json
Labels: UX
