Repository microsoft/vscode-java-dependency, pull requests merged in 2020-09, with the labels that each got.

#324 Fix backbutton issue
  src/exportJarFileCommand.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/IExportJarStepExecutor.ts
  src/exportJarSteps/IStepMetadata.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
  src/exportJarSteps/ResolveMainMethodExecutor.ts
  src/exportJarSteps/utility.ts
Labels: bug

#332 feat: Add 'Reveal in Java Projects' in editor titile context
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  package-lock.json
  package.json
  src/constants.ts
  src/extension.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/dependencyExplorer.ts
Labels: enhancement

#333 chore: Change 'never' to 'false' in when clause
  package.json
Labels: eng

#335 feat: Add 'create new class/package' into the view context menu
  package.json
  src/explorerCommands/new.ts
Labels: enhancement

#340 bugfix: Fix the bug that the explorer will be out-of-sync occasionally
  src/syncHandler.ts
  src/utils/Lock.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/hierarchicalPackageNode.ts
Labels: bug

#341 bugfix: Fix the NPE when focus on the output channel
  src/views/dependencyExplorer.ts
Labels: bug
