Repository microsoft/vscode-java-dependency, pull requests merged in 2020-10, with the labels that each got.

#343 feat: Add 'delete' into the view context menu
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/constants.ts
  src/explorerCommands/delete.ts
  src/explorerCommands/utils.ts
  src/views/PrimaryTypeNode.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/dependencyExplorer.ts
  src/views/fileNode.ts
Labels: enhancement

#342 Specific target folder when exporting jar and enhancement of jdtls.ext
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  package-lock.json
  package.json
  package.nls.json
  package.nls.zh.json
  src/exportJarFileCommand.ts
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/IStepMetadata.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
  src/exportJarSteps/ResolveMainMethodExecutor.ts
  src/exportJarSteps/utility.ts
  src/java/jdtls.ts
  src/settings.ts
  src/views/dependencyDataProvider.ts
Labels: enhancement

#348 Prepare for 0.14.0 release
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
Labels: eng

#352 Fix Status Bar bug when exporting jar
  src/exportJarSteps/GenerateJarExecutor.ts
Labels: bug

#353 feat: Add 'rename' into the view context menu
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/explorerCommands/delete.ts
  src/explorerCommands/rename.ts
  src/explorerCommands/utils.ts
  src/views/dependencyExplorer.ts
Labels: enhancement

#359 fix: sort the children for folder nodes
  src/views/folderNode.ts
Labels: bug

#361 test: Add test cases for new context value
  test/explorer/contextValue.test.ts
Labels: eng

#360 Upgrade the icon of export jar
  package-lock.json
  package.json
Labels: UX

#356 refactor Trie.ts to extend its availability
  src/views/nodeCache/Trie.ts
  src/views/nodeCache/explorerNodeCache.ts
Labels: eng

#365 feat: Add context value for folder
  package.json
  src/constants.ts
  src/explorerCommands/utils.ts
  src/views/folderNode.ts
  test/explorer/contextValue.test.ts
Labels: enhancement
