Repository microsoft/vscode-java-dependency, pull requests merged in 2020-12, with the labels that each got.

#401 fix: Prevent multiple calls of reveal() at the same time
  package.json
  src/views/dependencyExplorer.ts
Labels: regression

#402 refactor: Error reporting and null check in export jar
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/IExportJarStepExecutor.ts
  src/exportJarSteps/IStepMetadata.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
  src/exportJarSteps/ResolveMainClassExecutor.ts
  src/exportJarSteps/utility.ts
Labels: eng

#389 refactor: Fix null check and implicit any
  src/ExperimentationService.ts
  src/build.ts
  src/commands.ts
  src/controllers/libraryController.ts
  src/explorerCommands/new.ts
  src/explorerCommands/utility.ts
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
  src/exportJarSteps/ResolveMainClassExecutor.ts
  src/java/hierarchicalPackageNodeData.ts
  src/java/jdtls.ts
  src/settings.ts
  src/syncHandler.ts
  src/views/PrimaryTypeNode.ts
  src/views/containerNode.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/dependencyExplorer.ts
  src/views/documentSymbolNode.ts
  src/views/explorerNode.ts
  src/views/fileNode.ts
  src/views/folderNode.ts
  src/views/hierarchicalPackageNode.ts
  src/views/hierarchicalPackageRootNode.ts
  src/views/nodeCache/Trie.ts
  src/views/nodeCache/explorerNodeCache.ts
  src/views/packageNode.ts
  src/views/packageRootNode.ts
  src/views/projectNode.ts
  src/views/symbolNode.ts
  src/views/workspaceNode.ts
  test/gradle-suite/projectView.test.ts
  test/maven-suite/projectView.test.ts
  test/simple-suite/projectView.test.ts
  test/suite/contextValue.test.ts
  tsconfig.json
Labels: eng

#406 fix: Cannot show JDK class node in hierarchical mode
  src/views/hierarchicalPackageNode.ts
Labels: regression

#407 refactor: Change method signature to Promise
  src/views/containerNode.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/documentSymbolNode.ts
  src/views/fileNode.ts
  src/views/folderNode.ts
  src/views/hierarchicalPackageNode.ts
  src/views/packageNode.ts
  src/views/packageRootNode.ts
  src/views/projectNode.ts
  src/views/symbolNode.ts
  src/views/workspaceNode.ts
Labels: eng

#416 chore: prepare for 0.16.0
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
Labels: eng

#415 fix: Cannot new classes/packages for unmanaged folders
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
  src/explorerCommands/new.ts
  test/shared.ts
Labels: bug

#420 fix: Exporting Jar lasts all time in unmanaged folders
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
  src/exportJarSteps/GenerateJarExecutor.ts
  src/exportJarSteps/ResolveJavaProjectExecutor.ts
Labels: regression

#417 fix: NPE error when open non-project file
  src/utility.ts
  src/views/dataNode.ts
  src/views/dependencyDataProvider.ts
  src/views/dependencyExplorer.ts
Labels: bug

#423 ux: Add contextual title and icon for Java Project explorer
  package.json
Labels: UX

#425 fix: Cannot expand for multi-module project
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
Labels: bug

#426 feat: Make openFile experience consistent with built-in trees
  package-lock.json
  package.json
  src/commands.ts
  src/extension.ts
  src/utility.ts
  src/views/PrimaryTypeNode.ts
  src/views/dependencyDataProvider.ts
  src/views/dependencyExplorer.ts
  src/views/fileNode.ts
  src/views/symbolNode.ts
Labels: enhancement

#429 fix: Export Jar wizard shows main classes from libraries
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
Labels: bug
