Repository microsoft/vscode-java-dependency, pull requests merged in 2021-01, with the labels that each got.

#435 fix: No context menu when explorer is in hierarchical mode
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageParams.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/Trie.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/TrieNode.java
  src/views/packageRootNode.ts
Labels: bug

#437 feat: Add test metadata to the nodes
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  src/utility.ts
  src/views/PrimaryTypeNode.ts
  src/views/hierarchicalPackageNode.ts
  src/views/hierarchicalPackageRootNode.ts
  src/views/packageNode.ts
  src/views/packageRootNode.ts
  src/views/projectNode.ts
  test/suite/contextValue.test.ts
  tslint.json
Labels: enhancement

#434 Fix add libraries dialog not working on Linux
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/controllers/libraryController.ts
Labels: bug, enhancement

#441 chore: prepare for 0.17.0
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
Labels: eng

#442 fix: High severity caused by outdated version of `vscode-tas-client`
  package-lock.json
  package.json
Labels: eng

#443 fix: Modify CHANGELOG.md for Linux users when adding library folders
  CHANGELOG.md
Labels: eng

#446 fix: No pom.xml in the root path of exported jar file
  src/exportJarSteps/ExportJarTaskProvider.ts
Labels: bug

#447 fix: Cannot show compilation units under the default package
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/Trie.java
Labels: regression

#448 chore: Remove CRLF restriction and Add extension recommendation
  .vscode/extensions.json
  jdtls.ext/check_style.xml
Labels: eng

#450 fix: Cannot list multi-module projects properly
  jdtls.ext/com.microsoft.jdtls.ext.core/.classpath
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
Labels: bug
