Repository microsoft/vscode-java-dependency, pull requests merged in 2021-08, with the labels that each got.

#535 fix: Do not activate the Java Language Server
  src/extension.ts
Labels: bug

#534 chore: Support tests in VSCode 1.59
  package-lock.json
  package.json
  test/ui/command.test.ts
  test/ui/index.ts
Labels: eng

#533 feat: Support new file contribution
  package-lock.json
  package.json
  src/commands.ts
  src/explorerCommands/new.ts
  src/views/dependencyExplorer.ts
Labels: enhancement
