Repository microsoft/vscode-java-dependency, pull requests merged in 2022-08, with the labels that each got.

#682 chore(deps): Update dependencies
  ThirdPartyNotices.txt
  jdtls.ext/com.microsoft.jdtls.ext.core/.classpath
  jdtls.ext/com.microsoft.jdtls.ext.core/.project
  jdtls.ext/com.microsoft.jdtls.ext.core/.settings/org.eclipse.core.resources.prefs
  jdtls.ext/com.microsoft.jdtls.ext.core/.settings/org.eclipse.jdt.core.prefs
  jdtls.ext/com.microsoft.jdtls.ext.core/.settings/org.eclipse.m2e.core.prefs
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/build.properties
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/JarFileContentProvider.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  jdtls.ext/target.target
  package-lock.json
  package.json
Labels: dependencies

#683 fix: Activation events not working
  package.json
Labels: bug

#685 fix: Do not allow craeting new types in resource folder
  src/explorerCommands/new.ts
  src/views/packageRootNode.ts
Labels: bug

#684 fix: Remove the limitation of only displaying invisible projects
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
Labels: bug

#686 chore: remove ASKUSER option
  src/tasks/buildArtifact/GenerateJarExecutor.ts
  src/tasks/buildArtifact/utility.ts
Labels: eng
