Repository microsoft/vscode-java-dependency, pull requests merged in 2022-07, with the labels that each got.

#657 Remove symbolNode.ts
  src/views/DragAndDropController.ts
  src/views/baseSymbolNode.ts
  src/views/documentSymbolNode.ts
  src/views/symbolNode.ts
Labels: eng

#658 chore: Bump dependencies version
  package-lock.json
  package.json
Labels: dependencies

#659 chore: Update test framework to `@vscode/test-electron`
  package-lock.json
  package.json
  test/index.ts
Labels: eng

#661 fix: Cannot drag from VS Code's file explorer to Java Project explorer
  package-lock.json
  package.json
  src/views/DragAndDropController.ts
Labels: bug

#662 chore: Update `globby` and `copy-webpack-plugin`
  package-lock.json
  package.json
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/exportJarSteps/GenerateJarExecutor.ts
Labels: dependencies

#660 feat: Support run build from tasks
  extension.bundle.ts
  package.json
  package.nls.json
  package.nls.zh.json
  src/build.ts
  src/commands.ts
  src/extension.ts
  src/java/jdtls.ts
  src/tasks/build/buildTaskProvider.ts
  test/suite/buildTask.test.ts
Labels: enhancement

#663 feat: Add build project command into context menu
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/views/dependencyDataProvider.ts
Labels: enhancement

#664 ui: Add submenu for Maven and Gradle
  package.json
  package.nls.json
  package.nls.zh.json
  src/views/dependencyDataProvider.ts
Labels: UX

#669 Add zh-tw locale
  package.nls.zh-tw.json
Labels: enhancement, eng

#672 chore: Rename to package.nls.zh-cn.json
  package.nls.zh-cn.json
Labels: eng

#671 feat: Show reload button at editor title when there is reload required diagnostics
  package.json
  package.nls.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/commands.ts
  src/constants.ts
  src/extension.ts
  test/maven-suite/context.test.ts
Labels: enhancement

#667 UX: Change export task type to `java (buildArtifact)`
  package.json
  src/commands.ts
  src/constants.ts
  src/exportJarSteps/ExportJarTaskProvider.ts
  src/extension.ts
  src/tasks/migration/CodeActionProvider.ts
  src/tasks/migration/DiagnosticProvider.ts
  src/tasks/migration/utils.ts
  test/maven-suite/exportJar.test.ts
  test/maven/.vscode/tasks.json
Labels: UX

#673 chore: Prepare for 0.21.0
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
Labels: eng

#674 fix: Only show migration Quick fixes for opened tasks.json
  src/tasks/migration/DiagnosticProvider.ts
  src/tasks/migration/utils.ts
Labels: bug

#675 UX: Polish messages for task type migration
  src/tasks/migration/CodeActionProvider.ts
  src/tasks/migration/DiagnosticProvider.ts
Labels: UX

#678 refactor: Move export jar related code under tasks folder
  extension.bundle.ts
  src/extension.ts
  src/java/jdtls.ts
  src/tasks/buildArtifact/BuildArtifactTaskProvider.ts
  src/tasks/buildArtifact/GenerateJarExecutor.ts
  src/tasks/buildArtifact/IExportJarStepExecutor.ts
  src/tasks/buildArtifact/IStepMetadata.ts
  src/tasks/buildArtifact/ResolveJavaProjectExecutor.ts
  src/tasks/buildArtifact/ResolveMainClassExecutor.ts
  src/tasks/buildArtifact/migration/CodeActionProvider.ts
  src/tasks/buildArtifact/migration/DiagnosticProvider.ts
  src/tasks/buildArtifact/migration/utils.ts
  src/tasks/buildArtifact/utility.ts
  src/views/dependencyDataProvider.ts
  test/maven-suite/buildArtifact.test.ts
Labels: eng

#679 chore: Remove unused module
  .vscode/settings.json
  javaConfig.json
  jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.activator/build.properties
  jdtls.ext/com.microsoft.jdtls.ext.activator/plugin.xml
  jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.activator/src/com/microsoft/jdtls/ext/activator/JdtlsExtActivator.java
  jdtls.ext/pom.xml
  test/suite/buildTask.test.ts
Labels: eng

#681 fix: Scan two levels of directories for activation indicators
  package.json
Labels: eng
