Repository microsoft/vscode-java-dependency, pull requests merged in 2023-05, with the labels that each got.

#765 feat: Support create Graal Cloud Native projects.
  src/controllers/projectController.ts
Labels: enhancement

#769 chore: Prepare for 0.23.0
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.target/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
Labels: eng

#771 fix: Cannot open file explorer from welcome view.
  CHANGELOG.md
  package.json
Labels: bug
