Repository microsoft/vscode-java-dependency, pull requests merged in 2023-04, with the labels that each got.

#729 refactor: Use visitor pattern to get the explorer nodes
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/JavaResourceVisitor.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceSet.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceVisitor.java
  src/views/folderNode.ts
Labels: eng

#731 refactor: Use factory pattern to create explorer nodes
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/NodeKind.java
  package.json
  src/java/nodeData.ts
  src/views/containerNode.ts
  src/views/dataNode.ts
  src/views/folderNode.ts
  src/views/hierarchicalPackageNode.ts
  src/views/hierarchicalPackageRootNode.ts
  src/views/nodeFactory.ts
  src/views/packageNode.ts
  src/views/packageRootNode.ts
  src/views/projectNode.ts
  src/views/workspaceNode.ts
Labels: eng

#730 feat: Display non-java resources in the Project explorer
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceSet.java
  src/explorerCommands/rename.ts
  src/syncHandler.ts
  src/views/projectNode.ts
  test/gradle-suite/projectView.test.ts
  test/maven-suite/projectView.test.ts
  test/simple-suite/projectView.test.ts
Labels: enhancement

#737 refactor: Simplify the settings change event handling
  src/settings.ts
  src/views/dependencyDataProvider.ts
Labels: eng

#739 fix: Apply 'files.exclude' to Java Projects explorer
  CHANGELOG.md
  src/java/jdtls.ts
  src/settings.ts
  test/maven-suite/projectView.test.ts
  test/maven/.hidden
  test/maven/.vscode/settings.json
Labels: bug

#741 feat: Re-organize the new class & package commands
  package.json
  package.nls.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/commands.ts
  src/explorerCommands/new.ts
  src/extension.ts
  src/views/PrimaryTypeNode.ts
  test/suite/contextValue.test.ts
Labels: enhancement

#742 feat: Support creating new files/folders in Java Project explorer
  CHANGELOG.md
  package.json
  package.nls.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/commands.ts
  src/explorerCommands/new.ts
  src/views/PrimaryTypeNode.ts
  src/views/dependencyExplorer.ts
  test/suite/contextValue.test.ts
Labels: enhancement

#744 feat: Show non Java Projects in the Java Projects explorer
  CHANGELOG.md
  extension.bundle.ts
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  src/java/jdtls.ts
  test/maven-suite/projectView.test.ts
Labels: enhancement

#745 fix: Show 'module-info.java' at source roots
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/JavaResourceVisitor.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceSet.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceVisitor.java
  test/maven-suite/projectView.test.ts
  test/maven/pom.xml
  test/maven/src/main/java/module-info.java
Labels: bug

#747 fix: Better handling the import error hint
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  src/views/dependencyDataProvider.ts
Labels: regression

#749 feat: Introduce a setting to control whether non-Java resources should be filtered
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
  package-lock.json
  package.json
  package.nls.json
  package.nls.zh-cn.json
  src/commands.ts
  src/java/jdtls.ts
  src/settings.ts
  src/views/dependencyExplorer.ts
  test/maven-suite/projectView.test.ts
Labels: enhancement

#753 chore: Update VS Code engine version to 1.77.0
  package-lock.json
  package.json
Labels: eng

#752 fix: Display compilation units which does not have a primary type
  CHANGELOG.md
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/NodeKind.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
  jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/JavaResourceVisitor.java
  src/java/nodeData.ts
  src/views/dataNode.ts
  src/views/nodeFactory.ts
  test/maven-suite/projectView.test.ts
  test/maven/src/main/java/com/mycompany/app/package-info.java
Labels: bug

#754 feat: Support create different kind of resources from inline new button.
  package.json
  package.nls.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/commands.ts
  src/explorerCommands/new.ts
  src/views/dependencyExplorer.ts
Labels: enhancement

#755 Change the setting 'java.project.explorer.filters' to 'java.project.explorer.showNonJavaResources'
  CHANGELOG.md
  package.json
  package.nls.json
  package.nls.zh-cn.json
  src/commands.ts
  src/settings.ts
  src/views/dependencyExplorer.ts
  test/maven-suite/projectView.test.ts
Labels: enhancement

#756 chore: Prepare for 0.22.0
  CHANGELOG.md
  README.md
  jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
  jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
  jdtls.ext/com.microsoft.jdtls.ext.target/pom.xml
  jdtls.ext/pom.xml
  package-lock.json
  package.json
  test/ui/index.ts
Labels: eng

#760 fix: spelling mistake in workbench Java Projects
  package.nls.json
Labels: bug
